import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export async function writeSourcePackage({ outDir, sourcePackage }) {
  const root = join(outDir, 'source-package');
  const written = [];
  for (const file of sourcePackage.files) {
    const target = join(root, file.path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, file.content || defaultContent(file));
    written.push(target);
  }
  return written;
}

function defaultContent(file) {
  return `// Generated by AABC Labs v3 reference runtime.\n// File kind: ${file.kind}\n`;
}
